// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// tl_main package generated by `tlgen.py` tool

package tl_main_pkg;

  localparam logic [31:0] ADDR_SPACE_RAM_INSTR = 32'h 00000000;
  localparam logic [31:0] ADDR_SPACE_RAM_DATA  = 32'h 00100000;
  localparam logic [31:0] ADDR_SPACE_NOC_FIFO  = 32'h 00200000;

  localparam logic [31:0] ADDR_MASK_RAM_INSTR = 32'h 00007fff;
  localparam logic [31:0] ADDR_MASK_RAM_DATA  = 32'h 000fffff;
  localparam logic [31:0] ADDR_MASK_NOC_FIFO  = 32'h 00000fff;

  localparam int N_HOST   = 3;
  localparam int N_DEVICE = 3;

  typedef enum int {
    TlRamInstr = 0,
    TlRamData = 1,
    TlNocFifo = 2
  } tl_device_e;

  typedef enum int {
    TlCorei = 0,
    TlCored = 1,
    TlExternalif = 2
  } tl_host_e;

endpackage
